### ISSUE TITLE
Parsing of image file extensions on .jpeg files

### ISSUE THREAD

**Issue by luciorq** [nvelden/Employee_Directory_CRUD#1]
App don't accept `.jpeg` extensions but accept `.jpg`.

The file gets uploaded corretly.

![image](https://user-images.githubusercontent.com/22479186/103094460-53717c00-45dc-11eb-85c0-bcaf18e8f4fe.png)

But when trying to save appears the following message.

![image](https://user-images.githubusercontent.com/22479186/103094505-7d2aa300-45dc-11eb-815f-0bc5fa07d2b6.png)

It doesn't happen if the extension is manually renamed to `.jpeg`.

**Comment by luciorq** [comment]
Actually alll those are valid extensions for JPEG files:

.jpg, .jpeg, .jfif, .pjpeg, .pjp, .jpe, and .jif

**Comment by nvelden** [comment]
Thanks a lot for your comment! I updated the list of allowed file extensions. Hope that solves the issue.
